### PR TITLE
Example fixes

### PR DESCRIPTION
**Pull request by gkellogg**
I went through and fixed many examples, one of which was actually causing my RDFa processor to hang! Everything else should be non-controversial, but there are some issues that indicate properties might be misnamed.

There are many more markup issues, and it would be great if new examples passed some form of validation before being incorporated. These were identified using a command-line tool in the linter.

### CODE REVIEW

**Comment by danbri** [comment]
Just to say a huge thanks for doing these. There's a bit of administrivia to do first before integrating but ... thanks - much appreciated :)

**Comment by danbri** [comment]
Ok I've merged in https://github.com/schemaorg/schemaorg/pull/260 ... can we close this version? 

I made the %20 tweak afterwards.

Suggestions for better workflow welcomed - would you prefer I ask the original pull request to be reconfigured to another branch? in this case I wanted it against sdo-stantz rather than master branch, and it seemed easier just to make another quick pull request. I couldn't see a way to change this one myself.

**Comment by scor** [comment]
You can change the target branch once the pull request is created, you have to create a new one, as inconvenient as it is...

What if you set the default branch and adjusted it accordingly after each release? https://help.github.com/articles/setting-the-default-branch/ - pull request will be created against that branch by default.

**Comment by danbri** [comment]
Thanks @scor just what I was looking for! :)

**Comment by danbri** [comment]
Related - I've updated https://github.com/schemaorg/schemaorg/issues/53 with a link to the results of re-running this linter against today's version of sdo-stantz: https://gist.github.com/danbri/c5fef76dcf89bc23bdb6

**Pull request closed without merging**
