### PR TITLE
Issue #137: Created InteractionCounter type and properties to supersede UserInteraction.

### PR DESCRIPTION
**Pull request by vholland**

### CODE REVIEW

**Comment by danbri** [comment]
Thanks @vholland. @elf-pavlik - care to take a look?

**Comment by zazi** [comment]
The term 'interaction' is included in every property and class that is related to this issue, I doubt that this is a best practice for good vocabulary design. Unfortunately, it is obviously necessary to keep everything under the schema.org namespace ... ;)

**Comment by danbri** [comment]
@zazi yes it natural consequence of various design tradeoffs, to drift towards having soft / pseudo namespaces in various places. Although it might not look particularly elegant it does keep several things simpler for publishers/webmasters. I think we can live with it for now.

**Comment by elf-pavlik** [comment]
@vholland LGTM :smile: thank you!

1) I wonder why *userInteractionCount* and not simply *interactionCount* ?
2) At some point we still could try to find a way of linking to the collection/container with actual references to all the interactions (e.g. Comment - all the comments, Share - all the shares, Follow - all the followers). In lines of what I tried to brainstorm in this comment https://github.com/schemaorg/schemaorg/issues/137#issuecomment-56270890)

**Comment by vholland** [comment]
@elf-pavlik I was going to use `interactionCount`, but that already exists with different semantics. It seemed confusing to completely change the property's meaning. 

If people would rather, I can go back to that name.

**Comment by elf-pavlik** [comment]
I just noticed
* https://schema.org/downvoteCount
* https://schema.org/upvoteCount
* https://schema.org/answerCount
* ...

https://schema.org/docs/search_results.html#q=count

**Comment by danbri** [comment]
Merged in. We have some work on deprecation UI, but the new stuff shows up, e.g. http://webschemas.org/InteractionCounter (also in sdo-ganymede test site)

**Comment by vholland** [comment]
SGTM. Feel free to kick back merges back to me.

**Comment by unor** [comment]
Some HTML changes: https://github.com/schemaorg/schemaorg/pull/593

**Pull request merged**
