### PR TITLE
Broadened the domain of issn and updated its definition.

### PR DESCRIPTION
**Pull request by nicolastorzec**
Proposed fix for #1640

### CODE REVIEW

**Comment by nicolastorzec** [comment]
Updated description of _issn_ per #1640

**Comment by danbri** [comment]
LGTM. Do you know if these are actually used much with datasets in practice?

**Comment by danbri** [comment]
Minor bug: we added domainIncludes of "Website" instead of "WebSite".

Odd, the runs-in-cloud test integration should have caught this. Maybe I missed it? 

I caught it via commandline test runner. Fixing.

**Comment by nicolastorzec** [comment]
Re: ISSN and datasets, dataset publishers don't use ISSN in my experience. However, research datasets often come with a DOI, e.g. via DataCite.

(Re: domain validation, I didn't see anything suspicious at the time either)

**Comment by ostephens** [comment]
It's worth noting a difference between the use case for DOIs and ISSNs - the former is meant to permanently identify a static resource, while the latter is specifically for a resource where updates or additions are issued periodically. An ISSN is also specific to the publication in/on a specific medium.

My experience reflects what @nicolastorzec says - ISSNs not usually used for datasets but it may depend on your definition of 'dataset'! ISSNs *are* used for databases (see http://www.issn.org/understanding-the-issn/what-is-an-issn/) with updating content - for example the the AgroForsetTree database (http://www.worldagroforestry.org/output/agroforestree-database) has an ISSN - but only for it's CD-ROM incarnation (2079-1399)

**Pull request merged**
