### PR TITLE
fix example for #2811

### PR DESCRIPTION
**Pull request by alex-jansen**

### CODE REVIEW

**Review by RichardWallis — APPROVED** [review]

**Comment by gkellogg** [comment]
Note that the (long overlooked) PR #2845 includes another fix in that same example file: https://github.com/schemaorg/schemaorg/pull/2845/files#diff-ff92f56b11a8e372a9cf8b185c6e449418e415bfd1731f6bc7e6beb7e8ac25ad

**Comment by danbri** [comment]
I have just merged #2845 - is this PR now redundant, or does the example need attention still?

**Comment by RichardWallis** [comment]
It still needs applying

**Comment by danbri** [comment]
Got it, merging!

**Comment by alex-jansen** [comment]
Thanks Dan!

**Pull request merged**
