### PR TITLE
Add InstructionSet

### PR DESCRIPTION
**Pull request by robdodson**
This is a continuation of the work started in https://github.com/schemaorg/schemaorg/pull/1087

- Recipe now inherits from InstructionSet
- Did my best to inherit subproperties but would love additional input
- Continued to use `yield` instead of `outcome` because `outcome` already [expects a MedicalEntity](http://health-lifesci.schema.org/outcome) and I wasn't sure if we'd want that in a Recipe?

If possible, I'd love for folks to review what's here so far and once we've settled on names and structure I can add in more examples.

@danbri PTAL

### CODE REVIEW

**Comment by danbri** [comment]
@vholland any comments?

Main concern for me is that InstructionSet sounds like computer hardware chips. We can always tweak "outcome" if needed, but the definition will be vague.

**Comment by vholland** [comment]
I have similar issues with InstructionSet, but don't have good ideas for an alternative. HowToInstructions seems odd.

I'm a little confused by ```supplies``` and ```instructionSupplies```.

- Do we need both? We should be able to infer whether the supplies apply to the instructions as a whole or an individual step based on the property subject.
- Do those properties need to accept an ItemList? If the supplies themselves don't need to be ordered, authors should be able to repeat the property or use an array as appropriate.

**Comment by robdodson** [comment]
Some other options:

- `HowToGuide`
- `SetOfInstructions`
- `Guide`
- `Tasks`

> I'm a little confused by supplies and instructionSupplies.

I can use `supplies` throughout. I should also update the PR to use `estimatedCost` throughout instead of `estimatedSupplyCost`.

> Do those properties need to accept an ItemList? If the supplies themselves don't need to be ordered, authors should be able to repeat the property or use an array as appropriate.

Being a bit of a schema.org newb I don't know the right answer to this :D happy to defer to whatever you guys think is most appropriate.

**Comment by dbiollo** [comment]
Sorry to jump in on the conversation uninvited, but I've been looking on schema.org for something for how-to pages and this InstructionSet looks like it would fit the bill. Is this pull request still going ahead since it's been in the works for a while? 

I'd toss in "InstructionManual" and second "HowToGuide" as suggestions for the type name.

**Comment by robdodson** [comment]
I haven't had time to work on it. @dbiollo if you're interested in picking it up that would be awesome.

**Comment by danbri** [comment]
I believe this was handled by http://schema.org/HowTo http://schema.org/docs/releases.html#g647 #647 #1616

**Pull request closed without merging**
