### PR TITLE
Add Subclass of Creative Work to Computer Language

### PR DESCRIPTION
**Pull request by thadguidry**
So that we have access to nice properties like 'creator' and 'dateCreated' among others.

### CODE REVIEW

**Comment by danbri** [comment]
Could equally be considered a Product? How about we look at how many properties are directly applicable and consider adding them directly?

**Comment by thadguidry** [comment]
@danbri if we go the direct route, we might piss off @mfhepp :)  but I would be OK with direct properties as well.

**Comment by vholland** [comment]
Out of curiosity, is there a use case for this? It might help ground the discussion.

**Comment by danbri** [comment]
I can think of use cases in a Wikidata or KG direction e.g. http://rigaux.org/language-study/diagram.html family tree of programming languages. Less obvious for our core Web search-y usecases, but it wouldn't be the first time we've strayed from that zone.

It might be (with extensions etc.) that we're getting to a level of richness where schema.org + extensions are useful for structuring databases rather than just annotating pages. I made a quick demo this morning to show how to populate a SPARQL db with our schemas - https://github.com/schemaorg/schemaorg/wiki/BlazeGraphSPARQLHowto

**Comment by thadguidry** [comment]
@vholland The use case is to 2 parts.

1. align with Wikidata mappings (and Infopanel on Wikimedia) that I am working towards

2. Align with Google's Base Info efforts for Computer Language entities and other entities (as well as Linked Data efforts starting at ACM.org and IEEE.org) ... Base Info is now showing like in this search: [https://www.google.com/#q=D+language](https://www.google.com/#q=D+language)  Notice the DEVELOPER, TYPING DISCIPLNE, STABLE RELEASE, and OS.

In particular, the Developer (creator) property is used as a reconciling qualifier for a computer language along with dateCreated, since funny enough, a few languages have the same name (some are older out of date historical languages that never reached full maturation).

I cannot speak for ACM or IEEE directly, but know of their efforts (helping search engines, by first helping themselves with Linked Data aggregation)

**Pull request closed without merging**
