### PR TITLE
Travis linter

### LINKED ISSUE #53: Linter warnings on schema.org examples
Update: https://gist.github.com/danbri/c5fef76dcf89bc23bdb6 has a fresh run against 2015-01-28th snapshot of sdo-stantz branch. -- @danbri

FYI, the following are warnings produced by the Structured-Data Linter for current schema.org examples:

[ earlier results removed for readability, see link above ] 

This was done through the following:
- clone http://github.com/structured-data/linter
- bundle install
- run the schema_examples rake task to generate all example files
- run `script/parse schema.org/*.html --lint --quiet

Changes to the schema.org RDFS need to be synchronized by updating the vocabulary in the RDF.rb gem, typically done after each release.

### PR DESCRIPTION
**Pull request by gkellogg**
Adds a Rakefile to make examples, and cooked schema.org vocabulary and context (needs fixing). Validates the vocabulary and each example on Travis-CI.
Fixes #53.

### CODE REVIEW

**Comment by lanthaler** [comment]
I guess you shouldn't override the existing Travis configuration :-)

**Comment by gkellogg** [comment]
It didn't seem there was on when I created it, but I can merge and have both run.

**Comment by gkellogg** [comment]
From commit, .travis.yml was a new file. Of course, it fails, because it's finding problems with examples, which is the whole point.

**Comment by gkellogg** [comment]
The PR was done to sdo-makemake, which does not use Travis. sdo-calisto does, so this should probably be merged against that and reset as a pull to sdo-calisto, or something else, after reconciling the two build languages. At the time I branched, sdo- makemake was the default branch.

**Comment by lanthaler** [comment]
> It didn't seem there was on when I created it, but I can merge and have both run.

I set it up roughly 3 weeks ago (#1467, #1468). You may be targeting an old wrong branch here (`schemaorg:sdo-makemake` instead of `schemaorg:sdo-callisto`)

**Comment by gkellogg** [comment]
Sounds like I should target master, then? I'll take care of this in the next day or so.

**Pull request closed without merging**
