### PR TITLE
fixing namespace errors pointed out in issue #2485

### PR DESCRIPTION
**Pull request by philbarker**
Minor changes fixing examples related to Course and CourseInstance.

### CODE REVIEW

**Comment by RichardWallis** [comment]
@philbarker 

This is failing integration tests:
eg. 
```data/ext/pending/issue-2534.rdfa:37: parser error : Opening and ending tag mismatch: span line 33 and div```

**Comment by philbarker** [comment]
@RichardWallis odd. I didn't edit that file.

**Comment by philbarker** [comment]
@RichardWallis  OK, fixed those errors by merging recent changes from master into this branch, but... now have new errors. Not sure from Travis error messages what these are from.  Thanks for the heads-up, will look at this again later. Let me know if you have any clues about what's wrong.

**Comment by philbarker** [comment]
@RichardWallis fixed now! (just merged in more changes from master branch) Thanks for highlighting problem.

**Comment by danbri** [comment]
Thanks, this looks good!

**Pull request merged**
