### PR TITLE
Expand domain of video & audio to Thing

### PR DESCRIPTION
**Pull request by RichardWallis**
As per Issue #1447  
Expand domain of _video_ property to _Thing_ plus update description to clarify use and preserve its continued suitability for current usage on _CreativeWork_.

> A video of, or video component of, the item. This can be a URL or a fully described VideoObject.

Only expanding the domain of _video_ creates an anomaly where any _Thing_ can have an _image_ or a _video_, but only CreativeWorks can also have an _audio_.  To remove the anomaly the domain and description of _audio_ is also expanded.

> An audio recording of, or audio component of, the item. This can be a URL or a fully described AudioObject.

### CODE REVIEW

**Comment by danbri** [comment]
Can we just attach them to CreativeWork, plus any other cases that emerge?

Cluttering Thing has a big effect across the site... /cc @rvguha

**Comment by RichardWallis** [comment]
As neither of the two cases referenced in the original issue (#1447) were CreativeWorks (a Tourist attraction and a MusicGroup) and the related issue (#292) references thing such as Events and Products; I think the 'adding them to other cases as they arise' approach will not be sufficient - in the current environment folks want to have videos of everything in the same way we get images of most any type of thing.

I understand the cluttering effect of adding things to Thing, but I think this is one of those cases.

**Comment by nickevansuk** [comment]
+1 here, `video` is native in HTML5, it should be native on `Thing` here too

**Comment by philbarker** [comment]
This seems to change the semantics of the property video from "here is a video which is embedded in this CreativeWork" to "here is a video of this Thing". 

I can see the arguments for having the latter, but it seems like a new property. Rather than clutter up Thing and all sub classes, how about a new property of perhaps of CreativeWork, `depicts` expected range: Thing,  definition: the thing shown or portrayed.

**Comment by nickevansuk** [comment]
Noting that `image` is currently used as "here is an image which is embedded in this CreativeWork", as well as "here is an image of this Thing".

I imagine the same debate happened in HTML5 with `<video>` vs `<embed>` (why define `video` as a first class citizen when you can just use `embed` to do it more generally), and I guess the logic goes that given that the web platform is moving towards native video in general, schema.org should follow suit.

**Comment by vholland** [comment]
+1 to @philbarker's point about not changing the definition of http://schema.org/video. We have http://schema.org/subjectOf in pending.

**Comment by nickevansuk** [comment]
I can see why http://schema.org/subjectOf is a great solution where the main subject of a given page is a Person, Organization, etc and authors want to mention there is a creative work about that entity (https://github.com/schemaorg/schemaorg/issues/1670), however this seems to be saying "here is an array of works related to this thing" which I would suggest is a disjoint use case compared with "here is a video of this Thing".

I suppose it comes down to the [perceived ubiquity of video](https://www.wordstream.com/blog/ws/2017/03/08/video-marketing-statistics)?

Asking the question in reverse, when `subjectOf` comes out of pending, would we advocate deprecating `image` in favour of using `subjectOf` to reference images relating to Things? If not, why not?

--

@vholland noting that you'd previously suggested `embeddedVideo` to resolve issues with changing the definition (https://github.com/schemaorg/schemaorg/issues/1447#issuecomment-329811219)?

As an aside: the JSON-LD example on [`video`](https://schema.org/video) is no longer valid as `MusicGroup` is not a `CreativeWork`.

**Comment by thadguidry** [comment]
@nickevansuk Your use case of "here is a video of this Thing" is handled already.  :)  Many folks just use VideoObject or MediaObject and then to describe the content you can fill in the
"caption", "about", "contentLocation", "genre", "keywords", "mainEntity", "mentions", "spatialCoverage", "temporalCoverage".

**Comment by nickevansuk** [comment]
Sure @thadguidry - we put together a [video on openactive.io](https://www.youtube.com/watch?v=a2FdmspmCNk) too to help explain it, feel like this might be the right PR to plug that ;)

In terms of fitness activities (physical activity opportunities across a range of sports, both physical and virtual): `Brand`, `Event`, and `Organization` all have videos about them. There's evidence that helping a participant understand what they can expect from an event increases their likelihood of attending, and video is a key part of that.

The Brand "Back to Netball" has a video: https://www.youtube.com/watch?v=N268gBOvnzo
The Organization "GoodGym" has a video here: https://www.youtube.com/watch?v=BPR0vhHgeWA
The Event "London Marathon" has a video here: https://www.youtube.com/watch?v=2KOLxQEfmCI

I understand that we could use subjectOf for this, however was hoping (as above) that given the amount of discussion and the existence of this pull request, that there'd be an appetite to bring `video` in line with `image`.

For example:

```
{
  "type": "Brand",
  "name": "Back to Netball",
  "description": "Running across England since 2010, over 60,000 women have taken part in Back to Netball and realised the benefits of getting involved.  From losing weight, developing the body’s cardiovascular system and improving muscle tone, taking part in Back to Netball is great for you in so many ways.",
  "logo": "http://hertsnetball.co.uk/js/plugins/imagemanager/files/B2N_logo.jpg", 
  "url": "https://www.englandnetball.co.uk/backtonetball/", 
  "video": [
    {
      "type": "VideoObject",
      "description": "Video explanation of the programme",
      "url": "https://www.youtube.com/watch?v=N268gBOvnzo",
      "duration": "T1M33S",
      "name": "What is Back to Netball?",
      "thumbnail": "http://example.com/js/plugins/imagemanager/files/video.png"
    }
  ]
}
```

**Comment by thadguidry** [comment]
@nickevansuk Sounds like you just need some support help with Schema.org first and foremost.  So...please use our mailing list as it is a much better place to provide you support...and if we hit roadblocks in describing your structured data needs, THEN we can come back into various Github issues and make a case for a new type or property or clarification.  Thanks!

Example for our mailing list:  Hi ! I work for OpenActive.io , where we do/help with X ...so... How would I go about telling the world that a video contains "blah", or is about "blah", or has some X relationship to X Thing ? Here are my entities and here's the relationships that I am trying to describe about them...

**Pull request closed without merging**
