### PR TITLE
Add CSV export of classes, properties, enumeration values (#390)

### PR DESCRIPTION
**Pull request by cygri**
This implements #390 (Add CSV export), and is part of the larger #208 (Add more export formats).

### CODE REVIEW

**Comment by cygri** [comment]
(Whoops, sent prematurely.)

There are three new URLs:

http://localhost:8080/docs/all-types.csv
http://localhost:8080/docs/all-properties.csv
http://localhost:8080/docs/all-enumerations.csv

I'm not sure about the best place to link them in the site, but am happy to take direction and add them.

**Comment by danbri** [comment]
Sorry this went quiet, and thanks again for doing this. @RichardWallis will take a look!

**Comment by danbri** [comment]
Ping @RichardWallis 

BTW I tried the 'checkout via commandline' github instructions but get a Git error ("fatal: Cannot update paths and switch to branch 'cygri-sdo-scripts' at the same time."). The branch still seems to exist, not sure what's up there.

**Comment by RichardWallis** [comment]
Superseded in release 3.1

**Comment by danbri** [comment]
While it makes sense to close this specific PR, I think we still have missing functionality here - documentation of structure, properties etc at least, possibly other tables, maybe escaping/subsetting HTML etc etc. But https://github.com/schemaorg/schemaorg/issues/390 is a reasonably place to track all that.

**Comment by rtroncy** [comment]
Naive suggestion: in the [DOREMUS](http://www.doremus.org/) project, we have developed https://github.com/Guhogu/owl2csv which generates useful CSV documentation of any ontology, detailing the direct and inferred properties, etc. Several CSV files are generated, for all classes, properties. This could easily be adapted to take into account the schema.org specific constructs (e.g. domainInclude). cc @delahousse who is managing this project

**Comment by RichardWallis** [comment]
@rtroncy That looks like an interesting development.

I suggest we see how the introduction of the current csv implementation is received/used/commentated on when it is released (in 3.2), then revisit this area if the need is clear.

Meanwhile tracking in issue (#390)

**Pull request closed without merging**
