### PR TITLE
Issue #768: Added broadcastOfEvent.

### PR DESCRIPTION
**Pull request by vholland**

### CODE REVIEW

**Comment by danbri** [comment]
Merged. I'll update test sites tomorrow.

Btw did you know ... if you add 'broadcastOfEvent' to the poorly named TYPES line in examples.txt it'll show the examples on the property page too? I'll edit that in later.

**Comment by danbri** [comment]
Ok, http://sdo-phobos.appspot.com/broadcastOfEvent now shows the example.

**Comment by vholland** [comment]
I didn't realize that. That is great!

**Comment by danbri** [comment]
We have some backlog to retro-tag, but let's add them for new examples at least

**Pull request merged**
