### PR TITLE
Fix references to www.schema.org to point to standardized non-www URLs

### PR DESCRIPTION
**Pull request by scor**

### CODE REVIEW

**Comment by danbri** [comment]
Thanks :) There were some quick fixes via master after sdo-phobos was created, I'll sort out that admin first...

**Comment by scor** [comment]
Happy to rebase this pull request on any branch. just when you're ready...

**Comment by danbri** [comment]
If you can point it at 'master' that would be great, thanks!

**Comment by danbri** [comment]
Thanks!

**Pull request merged**
