### PR TITLE
Add Event Series support

### PR DESCRIPTION
**Pull request by wikier**
(supersedes #446, provides an implementation for #447)

Currently `schema.org` misses support for event series. 

The following diagram depicts the proposal:

Event Series desing

The proposal tries to minimize the impact on the current vocabulary by reusing already available terms, for instance `hasPart`/`isPartOf`. The design is based on the assumption that is better to materialize descriptions of each event rather than base the model on using the [recurrence rule](http://www.kanzaki.com/docs/ical/rrule.html).

The [Salzburger Festspiele](http://www.salzburgerfestspiele.at/) could be the typical example where such construction would be necessary to model the different editions every summer.

This proposal has been developed by [Redlink GmbH](http://redlink.co) in the context of [TourPack](http://tourpack.sti2.at/), a research project partially funded by the Austrian Research Promotion Agency ([FFG](https://www.ffg.at/en)), under grant agreement no. 845600.

### CODE REVIEW

**Comment by danbri** [comment]
Thanks for this. I think we'll have to tweak it somewhat though. Schema.org does not advocate for general use of Turtle currently (RDFa + Microdata + JSON-LD give plenty of options), so we won't take the Turtle example into the site. For JSON-LD it could probably do with hand editing for publisher simplicity - I'm afraid the current file looks very machine generated and could say the same thing in a much smaller file.

**Comment by wikier** [comment]
Understood, @danbri. Take a look now, please.

**Comment by danbri** [comment]
Sorry, reverting - this changed core not just pending. My bad.

**Comment by wikier** [comment]
@danbri :-?

**Comment by danbri** [comment]
To explain properly: I thought I'd merge this to pick up your example, but it seems 1.) I've already done that manually 2.) the PR also included changes against data/schema.rdfa to define the vocabulary.

For this release (v3.0 in next few days) we'll stick with EventSeries as a pending extension, and I think all the files are in place for that already.  Also within pending let's keep things together under issue-447-* as the main filename, to avoid losing track of which things are where. 

As a next step the role of "Series" deserves some more consideration. It was more or less obsoleted previously by CreativeWorkSeries, not clear if it serves us any value as a common supertype here.

**Comment by danbri** [comment]
How does http://pending.webschemas.org/EventSeries look? Shall we take out the Series supertype for now?

**Comment by danbri** [comment]
I've convinced myself. I'll remove Series as a supertype.

**Pull request merged**
