### PR TITLE
Fixed wording for StructuredValue (Issue 394)

### PR DESCRIPTION
**Pull request by mfhepp**
This fixes issue 394.
https://github.com/schemaorg/schemaorg/issues/394

### CODE REVIEW

**Comment by mfhepp** [comment]
This also fixes issue #109

**Comment by danbri** [comment]
"Structured values are values that consist of sub-elements and thus have some kind of internal structure."

We haven't so far used the term "element" heavily; it sounds rather XML-oriented. Maybe something like "Structured values are used when the value of a property has more complex structure than simply being a textual value or reference to another thing"?

**Comment by mfhepp** [comment]
@danbri 
Hi Dan, 
I have seen that you fixed this locally, but I spotted two minor mistakes, which this pull request fixes.
Martin

**Comment by danbri** [comment]
Thanks! The "a" was a stylistic thing rather than a typo, but I can't claim same for ".." :)

**Pull request merged**
