### PR TITLE
Update sdo-website-examples.txt

### PR DESCRIPTION
**Pull request by idhamperdameian**
Fix something broken with conflict

### CODE REVIEW

**Comment by mfhepp** [comment]
If I understand correctly, this removes merge conflict markup, right?

**Comment by idhamperdameian** [comment]
Yes, you are right.

See incorrect an example affected by this change at
https://schema.org/WebSite

2016-06-03 14:08 GMT+07:00 Martin Hepp <notifications@github.com>:

> If I understand correctly, this removes merge conflict markup, right?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/schemaorg/schemaorg/pull/1195#issuecomment-223506839>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AC7zshE2IGbyS9iunziATM8Du4foCeuvks5qH9MEgaJpZM4ItPRt>
> .
>



-- 
Terima kasih.

**Comment by unor** [comment]
The (already merged) issue https://github.com/schemaorg/schemaorg/pull/1202 seems to be about the same issue.

**Comment by danbri** [comment]
Thanks @idhamperdameian @unor for the fixes! 

> $ grep '<<' *.txt

... finds nothing currently so I think we're in a stable state and have no similar mess. Thanks again!

**Pull request closed without merging**
