### PR TITLE
Introduce BioSchemas terms into pending

### PR DESCRIPTION
**Pull request by RichardWallis**
Implements issue #2862 which in turn implements proposed bioschemas terms from PR #2711.

#2711 introduced data/ext/bio for them definitions, this moves those definitions into pending

### CODE REVIEW

**Review by danbri — APPROVED** [review]
@AlasdairGray and I met today to go through these line by line.

We're merging this, and note for future improvements:

 * linking to design discussions would be very useful, and to works e.g. Darwin Core that have inspired the choices here.
 * acknowledge that the communities brought together around bioschemas can reasonably be expected to be kept in the loop for changes, tweaks, and improvements
 * expect to move Taxon under DefinedTerm, and anticipate potential changes in that area to ensure that other non-lifesci forms of taxonomy can be addressed coherently within schema.org.
 * note that /potentialUse needs clarification and an example.
 * suggest adding /MediaObject as a potential value for /hasRepresentation, to allow mime-typed formats to be easily described.
 * Note that BioChemEntity is a kind of organizational construct rather than an upper level ontology sort of a type.
 * We'll establish quarterly check-ins to review progress, collect implementation experience, review new vocabulary suggestions especially those motivated by data-consuming implementations.

**Comment by danbri** [comment]
https://webschemas.org/hasStatus is too general a property name, we should refine this. Suggestions, @AlasdairGray ?

**Comment by AlasdairGray** [comment]
@danbri, in order to not delay the release, we would suggest dropping the property. 

We had a discussion about this in our telcon today. We can't find the original motivation for the `hasStatus` property and those present noted several issues with the current proposal. However, we also saw the benefit of having a property to capture this sort of information, e.g. to capture if the Gene has been 'knocked out'. 

We've created an issue in the Bioschemas tracker ([Bioschemas:512](https://github.com/BioSchemas/specifications/issues/512)) to come back with a more detailed proposal in a future iteration.

**Comment by danbri** [comment]
Thanks, I'll comment it out for now!

**Pull request merged**
