### PR TITLE
Set up continous integration testing with Travis

### PR DESCRIPTION
**Pull request by lanthaler**
Travis needs to be enabled by one of the repo admins

### CODE REVIEW

**Comment by danbri** [comment]
Hmm would you mind re-sending the PR targetting sdo-callisto?

**Comment by lanthaler** [comment]
Sure, here it is: https://github.com/schemaorg/schemaorg/pull/1468

**Comment by danbri** [comment]
Thanks again for this, it was super helpful :)

one more q: is there any way, within the running tests, to see the outer environment i.e. which branch we are being tested against? I'd like to use that to warn if a PR is sent to 'master' branch.

**Comment by dbs** [comment]
I suggest simply adopting the standard git working practice of using master as the development branch against which would-be contributors should send pull requests. schema.org is one of the only projects I've participated in that breaks the "develop against master" pattern; adopting standard practice would reduce the friction required by newcomers to contribute to the project.

**Comment by thadguidry** [comment]
@danbri I agree with dbs on that... make master the development branch.

**Comment by danbri** [comment]
@dbs we have an organizational need for some kind of two-step staging, since schema.org itself doesn't change without its steering group approving each release-candidate bundle of integrated improvements. I was already thinking to ditch the release-named branches and have a single same-name-each-time dev branch, so I guess all we need to do is pick a new name for the "uptight", steering-group-reviewed branch from which schema.org is actually published. Is there an established convention for that? "releases", "published", etc? It is indeed time for a bit of a new year's refresh on these habits...

**Comment by thadguidry** [comment]
@danbri GitFlow-based workflows use "release" and use "develop" for development. Here's a cheatsheet that thousands of devs refer to each day: http://danielkummer.github.io/git-flow-cheatsheet/ - look at finishing up a release ... using GitFlow would probably simplify your lives.

**Comment by danbri** [comment]
"release" or "releases" sounds ok but now I'm getting mixed messages here on "master" vs "develop". @dbs any view?

**Comment by danbri** [comment]
see also https://barro.github.io/2016/02/a-succesful-git-branching-model-considered-harmful/

**Comment by lanthaler** [comment]
Sorry for the late reply, this completely slipped under my radar

> one more q: is there any way, within the running tests, to see the outer environment i.e. which branch we are being tested against? I'd like to use that to warn if a PR is sent to 'master' branch.

Yes, the [`TRAVIS_BRANCH`](https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables) environment variable tells you exactly that.

> "release" or "releases" sounds ok but now I'm getting mixed messages here on "master" vs "develop". @dbs any view?

To keep it simple and consistent with almost every other project on GitHub, I would use `master` for development and release (with tags) for officially blessed releases.

**Comment by gkellogg** [comment]
The CONTRIBUTING.md file should probably say this, so it shows up when doing a PR.

**Pull request merged**
