### PR TITLE
mission, Project, Goal, Objective, Task (Issue #1127)

### PR DESCRIPTION
**Pull request by westurner**
- | Issue: #1127

### CODE REVIEW

**Comment by westurner** [comment]
@richardwallis why did you close this PR?

- There is no feedback here
- There is no other proposed PR to solve for #1127
- I've been distracted and apparently no one other than @danbri realizes they need the ability to add structured markup for

**Comment by westurner** [comment]
Open questions from #1127:

Is there a *Completeable* supertype here?

Is *partOf* without a specific type restriction sufficient to model a graph of Completeables?

**Comment by RichardWallis** [comment]
@westurner sorry, it was an unexpected consequence of deleting an old stale branch 'sdo-deimos' which was way behind the current master.
Not sure why it didn't raise a warning, as it did for others with dependencies, to discourage the action.

Should be able to recreate against current master, from the listed commits.

**Comment by westurner** [comment]
Got it. NP

**Comment by westurner** [comment]
(I just sent an email to support@github.com about adding a note to PRs
closed by branch deletion)

**Pull request closed without merging**
