### PR TITLE
Introduced TermDefinition as a super type of CategoryCode

### PR DESCRIPTION
**Pull request by RichardWallis**
Changed CategoryCodes to TermDefinitions Issue #1775

Updated pending definitions and associated examples.

Plus dependant terms in other areas (_MedicalCode_ & _legislationType_)

### CODE REVIEW

**Comment by l00mi** [comment]
I am not well educated about the schema.org process. What is necessary that this PR gets accepted?

**Comment by RichardWallis** [comment]
Hi @l00mi,
Process is that between releases support, or otherwise, for the proposed change is voiced in the comments stream.   Ahead of the next release (3.4 is next - date yet to be fixed) PRs are added to the list of potential additions - an aggregating issue is usually created to handle this by @danbri.

Then subject to any further comments, the list of changes for the release is commented on and agreed by the members of the steering committee.  See also http://schema.org/docs/howwework.html

~Richard.

**Comment by l00mi** [comment]
Splendid, thank you for the thorough explanation @RichardWallis!

**Comment by danbri** [comment]
I believe this also attempts to address https://github.com/schemaorg/schemaorg/issues/251

I suggest exit criteria for moving it out of the pending area include 1.) examination of how / whether it applies to all existing schema.org properties that kinda-sorta take controlled code lists, but which currently say something like "expects URL or Text" 2.) some thought and explanation for how this relates to the (pretty widely adopted in its area) W3C SKOS work, particularly from the perspective of parties publishing controlled code lists, taxonomies and and other such enumerations.

**Comment by l00mi** [comment]
@RichardWallis if you need help with one of these tasks please ping me.

Personally I see that SKOS will be the full fledged version of a TermDefinition. 

Short possible propositions regarding SKOS:
1. Where a TermDefinition will be valid, a SKOS Concept is also valid.
2. There is a Property on the TermDefinition which is pointing to the according SKOS Concept.
3. We define that a TermDefinition Instance shall have a SKOS Concept class.

**Comment by RichardWallis** [comment]
If/when this proposal moves out of pending, as @danbri commented, we need to document how TermDefinition etc. relate to other areas (especially SKOS).

Such documentation should be targeted at a few groups:

- Those that have SKOS defined data and want to add Schema to it
- Those that want to build/markup new control code lists and understand, or have never heard of, SKOS

As @danbri also comments we need to review default, and or specific, use of TermDefinition as an expected type for schema properties.

Let's see how things map out initially in pending first.

**Pull request merged**
