### PR TITLE
Fix typo - acccommodation spelling

### PR DESCRIPTION
**Pull request by RehanSaeed**

### CODE REVIEW

**Comment by RichardWallis** [comment]
Thanks for the patch.  Unfortunately it will not work as these csv files are created from the main definition files at release time so would be overwritten.

The source needs fixing for http://schema.org/numberOfRooms.

@danbri I believe you are in master right now - do you want to fix this simple typo for numberOfRooms in schema.rdfa for the next release.

**Comment by RehanSaeed** [comment]
@RichardWallis Where is the source definition file?

**Comment by RichardWallis** [comment]
@RhanSaeed It's in data/schema.rdfa 

~Richard

**Comment by danbri** [comment]
Fixed in schema.rdfa, we'll regenerate the .csv at some point and it will be fixed automatically so I shall close this Pull Request. Thanks @RehanSaeed :)

**Pull request closed without merging**
