### PR TITLE
Fix for Issue #156. Minor cleanup. New tests for inverseOf and supercededBy

### PR DESCRIPTION
**Pull request by stuartrobinson**
Adds two new tests that make sure that inverseOf and supercededBy don't point to themselves. Fixes the following issue:

https://github.com/schemaorg/schemaorg/issues/156

### CODE REVIEW

**Comment by danbri** [comment]
Thanks @stuartrobinson. I'm still seeing a merge conflict but will pull this in and resolve any conflicts manually.

**Comment by danbri** [comment]
Merged manually. Thanks for this @stuartrobinson and apologies it took so long! Aiming for "PR inbox zero" now...

**Comment by jaygray0919** [comment]
May I ask a Google Structured Data Testing Tool (GSDTT) question here? Currently GSDTT does not process inverseOf. Will the planned changes here cascade into the way GSDTT processes inverseOf?

**Comment by danbri** [comment]
the Google SDTT does process all properties. It doesn't support the experimental idea of an inverse-itemprop attribute (or similar) for Microdata. Is that what you had in mind?

**Comment by jaygray0919** [comment]
Please ignore previous message - it was a brain fart. Our problem is not with `inverseOf`, which **is** properly processed by Google SDTT. Our problem is that we cannot use **@reverse** in schema.org. The **use case** is a follows: we use `Class` and `supercededBy` to define a tree. That allows us to specify the parent of a `Class` node. But we also need to specify that a `Class` node has children (i.e. `"@reverse": "rdfs:subClassOf"`). The reason is that we have an application that expects to see both  parent(s) and child/children when processing a tree structure. But we can't nudge a term into a schema.org `Class` structure that is not part of the data model (e.g. `"children": ("@reverse": "http://schema.org/Class"}`). Our solution is a total hack. We use `additionalType` as the term to specify children (we can tell our processor the term used for `children`). And then we hang our array of children on `additionalType`. Not elegant, but it works. Previously, I mentioned that we have the **MeSH** tree implemented using schema.org (and would contribute it to the greater good). This is the technique we use to build trees for our tree-processor.

Sorry to waste you time on an false aspersion. But it does allow me to explain one of the operating issues we face using schema.org. In many cases, we use `schema:Thing` and multiple **@graph** to handle extensions to a schema.org model. But we can't (or don't know how to) do it with trees. Hence the above hack.

FYI.

**Comment by danbri** [comment]
Interesting work-around :) If you were trying to tweak the Google SDTT's knowledge of schema.org by passing in additional schema definitions, I can reassure you that it won't work for all kinds of unexciting reasons. Is the MeSH work posted anywhere?

**Comment by jaygray0919** [comment]
First, here is MeSH in production (http://72.167.253.87/cgi-bin/flamenco.cgi/_ChEMATIC_v02_-_14-08-21_/Flamenco).

 [Tap F5 if the database is offline; it will load. This is a big database on an under-powered server, so please be patient when navigating the facets].

Currently, each facet is formulated using BFO and IAO. We now are converting the facet tree to schema.org, and I'll share when finished.

Separately, we have a tree that implements the ideas above. I'll post that to a Gist so you can see it. It is valid on Google SDTT. I'll also show you an application (our processor) that maps items to the tree. Those items are composed using schema.org. Further, the tree structure is properly rendered on @gkellogg Structure Data Linter (SDL).

But our processor needs to know the children; hence we purloin a term that Google SDTT will accept and use it as our key to define children. As an aside, our `d3.js` tree implementation (using the dendrogram pattern) **does not** need to know children. So that 'processor' can render a kosher schema.org tree.

Obviously, the right way to do this is with **@reverse**. When we use non-schema.org Controlled Vocabularies (CV) we can successfully use `@reverse rdfs:subClassOf`. In that case, the SDL  properly renders the tree.

Gimme a day or two to set this up; our folks are heads-down on composition tasks, so I'll need to do this myself. But your analysis is valuable so I'll set it the examples soon.

**Comment by jaygray0919** [comment]
@danbri here is the gist:
  https://gist.github.com/jaygray0919/669fc6693e9d25712c81142c06b0f727
It is Google SDTT valid.

Here is an application of the schema.org tree:
  http://ontomatica.com/public_new/project/test/Exhibit/publications/bibliography/bib_B/index.html

At this moment, only one publication is mapped to the technology tree. Our goal was simply to test the gist for one item.

Bottom line: we generate files for three processors; a facet navigation processor, a d3.js processor, and a SPARQL processor.

Given that we can generate schema.org trees (Class structures), items and their maps (relationships), we now can migrate examples like MeSH to a Google SDTT-valid platform.

The above is less of a statement and more of a question: are we going in the right direction? TY in advance for advice.

**Comment by jaygray0919** [comment]
@danbri Updated gist to remove null data.

**Pull request closed without merging**
