### PR TITLE
DOC: README.md: links to http://schema.org/version/2.0/ and source

### PR DESCRIPTION
**Pull request by westurner**
DOC,UBY: link to the web copy of schema.org release 2.0

### CODE REVIEW

**Comment by westurner** [comment]
Should this be here or on master? (hubflow: master (stable, tagged releases, hotfixes), develop (mainline), feature/, hotfix/, release/ ... https://westurner.org/tools/#hubflow ... https://datasift.github.io/gitflow/IntroducingGitFlow.html)

**Comment by westurner** [comment]
see #606

**Comment by danbri** [comment]
Sure, why not. Thanks!

**Comment by westurner** [comment]
Thanks!

**Pull request merged**
