### PR TITLE
Replaced meta tags with link tags for issue #77

### PR DESCRIPTION
**Pull request by stuartrobinson**
Changes to address the following issue:

https://github.com/schemaorg/schemaorg/issues/77

### CODE REVIEW

**Comment by danbri** [comment]
Thanks! Should these be @content or @href?

**Comment by stuartrobinson** [comment]
I think they should actually be @href. Let me update the branch.

**Comment by unor** [comment]
+1 for the changes to `data/examples.txt` (the RDFa needs these fixes, too, but this could come at a later point).

The issues in `data/sdo-website-examples.txt` seem to have been fixed in the meantime (nitpick in the current version: the `url` value for the Microdata example should be `http://example.com/` instead of `http://www.example.com/`).

**Comment by danbri** [comment]
Belatedly fixed and merged, including the s/www.example.com/example.com/ caught here by @unor. Thanks both!

**Comment by danbri** [comment]
Merged to wrong branch, reverting and committing manually. Apologies for the noise and thanks again!

**Pull request merged**
