### PR TITLE
New 'difficulty' property for Recipe

### PR DESCRIPTION
**Pull request by sergioredondo**
Many recipes websites label their recipes depending on the difficulty of elaboration, so this could be a new property for Recipe schema.

### CODE REVIEW

**Comment by vholland** [comment]
The term 'difficulty' might apply to a variety of things. Can we rename to something like 'recipeDifficulty' to avoid name collisions in the future?

**Comment by rvguha** [comment]
I agree, but the concept of 'how difficult these instructions are to
follow' applies to a number of things. Whilst 'difficulty' is too
ambiguous, 'recipeDifficulty' is too specific. Can we do something that
covers all 'howDifficultTheseInstructionsAreToFollow' with a better name
than that?

thanks,

guha

**Comment by thadguidry** [comment]
For recipes... I typically just count(verbs)...to get a taskDifficulty score.  Seems to work pretty good for my usage.  verbs like (bake, cover, mix, stuff, mash, grind, season, fry, toss, etc...)

**Comment by sergioredondo** [comment]
When I thought about this new property I meant 'Recipe Dificculty'. I imagine this new property with three possible values: Easy, Intermediate and Difficult. Of course, is up to the user who marks up the content to use whatever he/she wants, but in order to limit its use I think it's probably better to find a way to use only 3 possible values.

I like the option 'taskDifficulty', because it can be used not only for 'Recipes', but more types, so it can be a property for an upper level like 'CreativeWork' or 'Thing', although I prefer it being exclusive to 'Recipe'.

**Comment by thadguidry** [comment]
I want taskDifficulty (or an even better term 'difficultyRating') to not be
limited to an enum of 3 values of: Easy, Intermediate, and DIfficult.

I want support for a https://schema.org/PropertyValueSpecification
that way, we do not limit others but provide

I think difficultyRating might be a better choice on 2nd thought...subtle
alignment with AggregateRating and such which can later on aggregate the
most difficult and least difficult, etc...

**Comment by sergioredondo** [comment]
You're right Thad. I agree with you. 'difficultyRating' could be a great solution.

**Comment by vholland** [comment]
I like 'difficultyRating'. Instructional sites are common. I can see eventually having a general TaskInstruction type that could use this property.

**Comment by thadguidry** [comment]
Now we just need to decide...

Is a really great Recipe... one with a default difficultyRating of 1 or 5 ? :-)
I think the best recipes and styles are those around difficulty 2, like Jamie Oliver's 15 min quick recipes...a little effort and a lot of POW ! :-)

Seriously, we might want to look more at AggregateRating also... sorting out bestRating and worstRating.

Probably should not re-use those, but instead create new easiestRating and hardestRating properties underneath ?  Dunno.

Thoughts?

**Comment by chaals** [comment]
Well, assuming 1 means "only for experts with a well-equipped culinary laboratory and team" and 5 means "your 2-year-old can do it"…

difficultyRating looks good to me.

**Comment by sergioredondo** [comment]
I like 'difficulty Rating' option, but, against chaals's opinion, I imagine 1 as easy and 5 as difficult. But, thinking on snippets, the thing here is that this rate cannot be shown as stars by search engines, so I think is imperative to find another option to indicate this type of rating, thus distancing of 'aggregateRating'. That's why my initial thought of this rating was word-based, using some scale from Easy to Difficult (or from very easy to very difficult), so snippets could only shown a word, something like:
Difficulty: Easy
Don't know. What do you think about it?

**Comment by vholland** [comment]
Perhaps we create a new schema.org/DifficultyRating similar to schema.org/Rating. The properties are something like:

easiestRating
mostDifficultRating
ratingValue

Someone looking to provide a single word could use ratingValue.

Someone looking to provide a rating on a 1-5 scale could tell us how to interpret 1 and 5.

**Comment by thadguidry** [comment]
@sergioredondo  I agree that Stars might not be the best option to represent difficulty of tasks, recipes, etc.  The search engines can perhaps come up with a uniform symbol for this...let's let the industry choose that.

@vholland  Agreed on having ratingValue to hold text.
Agreed on schema.org/DifficultyRating (it will make publishers lives easier this way actually)
whatever you think is best for the property names, but I sorta prefer:

schema.org/DifficultyRating
- easiestRating
- hardestRating
- ratingValue

**Comment by sergioredondo** [comment]
Ok, I think it could be the best option. 

Excuse me, but I'm a newbie here. What's the next step?

**Comment by GraceMassaLanglois** [comment]
Just throwing this out, levelOfDifficulty - beginner, intermediate, advanced.

**Comment by fatso83** [comment]
This effort started nicely, but it seems to have died out. Re @sergioredondo's question, what can be done to further this initiative?

**Comment by thadguidry** [comment]
@sergioredondo Can you add an additional example file that uses the
numbered steps form (rather than paragraph) for the
property="recipeInstructions"  We'll need to support both
​forms ​
and teach users how to do it.
​  Real Example here:
http://allrecipes.com/recipe/241398/honey-balsamic-chicken/​

**Comment by thadguidry** [comment]
Once we have the other file example show numbered instructions...

I am +1 for getting this into Pending.

**Pull request closed without merging**
