### PR TITLE
add accessibility example to relevant properties

### PR DESCRIPTION
**Pull request by chaals**
Might as well show it there

### CODE REVIEW

**Comment by chaals** [comment]
Hopefully this makes the example we have of using the accessibility markup show up for each of the accessibility properties that it demonstrates

**Comment by danbri** [comment]
"hopefully"? care to test it locally? You need AppEngine SDK + Python, it is relatively painless...

**Comment by chaals** [comment]
I'll make a µdata example some time next week, in exchange for not testing it at least until then...

**Comment by danbri** [comment]
deal :) I might have a go too...

**Comment by chaals** [comment]
Added a scoped example to deal with questions people have.

I might wait until this gets merged before further additions...

**Comment by danbri** [comment]
Merged. Examples look good :) nice to have property pages with better examples...

**Comment by danbri** [comment]
e.g. http://webschemas.org/accessibilityFeature

**Pull request merged**
