### PR TITLE
CI: check the validity of the RDFa file

### PR DESCRIPTION
**Pull request by dunglas**
To prevent future errors those fixed in #1721.

### CODE REVIEW

**Comment by dunglas** [comment]
(The build will be green when #1721 will be merged.)

**Comment by dunglas** [comment]
@danbri, do you think you can merge #1721 and this one?

**Comment by danbri** [comment]
What is vnu, what does "java -jar dist/vnu.jar data/schema.rdfa" do, and what license is the code?

**Comment by danbri** [comment]
Ok, I see it's the world famous MIT-licensed HTML validator. Sure, though you might want to be consuming one of the distributed formats from http://schema.org/docs/developers.html instead of the HTML/RDFa/RDFS thing we use within the project.

**Comment by dunglas** [comment]
Thanks for the merge @danbri!

**Pull request merged**
