### PR TITLE
Responsive design commit series

### PR DESCRIPTION
**Pull request by dbs**
This branch includes a series of commits meant to improve the responsive design of schema.org for device display, and is meant to be the first steps towards addressing #490. More can certainly be done, but this is much more usable than the current experience, and makes very little impact on existing large-screen displays.

### CODE REVIEW

**Comment by rvguha** [comment]
Before much more effort is expended in this direction, lets take a step
back.

I am really not convinced at all that the Schema.org site needs to be
redone with with 'responsive design'.

guha

**Comment by dbs** [comment]
Google's "Mobile-Friendly Test" at https://search.google.com/test/mobile-friendly?id=TacwddyZ3zuudEcsBMGrIQ says "Page is not mobile friendly: This page can be difficult to use on a mobile device" and lists the following major issues:

* Text too small to read
* Viewport not set
* Clickable elements too close together

The branch I offered tackles the worst of these issues via minimal changes to the current schema.org CSS and code.

It's 2018. Having a website that requires zooming & side-to-side scrolling on phones, or that requires manually changing font size on hi-res laptop and desktop screens simply to be legible, stopped being acceptable years ago. And yes, many of us do consult schema.org on phones and hi-res laptop and desktop screens.

**Comment by rvguha** [comment]
This looks fine to me.

guha

**Comment by danbri** [comment]
I'm merging this in, but we have a minor conflict with the CSE fixes I've also just merged into master: https://github.com/schemaorg/schemaorg/pull/1857

The CSE fix puts generic header tags into a dedicated sub-template file which gets included during template processing: 

> ```<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />```

@dbs 's fix had a charset declaration in each file, using a different notation:

> ```<meta charset="utf-8">```

I'm resolving the conflict in favour of the abovementioned CSE-fix from  #1857 for now. Do we have any evidence that the http-equiv notation is any less mobile-friendly? It would be trivial to also add the charset attribute too, but let's not do it without reason.

**Comment by dbs** [comment]
@danbri `<meta charset="utf-8">` is HTML5 vs. the older XHTML syntax. Per https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta:

> The <meta> element with a charset attribute is a synonym for the pre-HTML5 `<meta http-equiv="Content-Type" content="text/html; charset=IANAcharset">`, where _IANAcharset_ contains the value of the equivalent charset attribute. This syntax is still allowed, although no longer recommended.

**Comment by danbri** [comment]
@dbs thanks, how '90s of us! I've merged this with the CSE fixes and updated to HTML5. Previously we had most of the site in Polyglot semi-XMLish, but I think that ship has sailed, so I've left this as 

```<meta charset="utf-8">```

rather than

```<meta charset="utf-8" />```

**Pull request merged**
