### PR TITLE
Issue #687: Added Barcode as a subtype of ImageObject.

### PR DESCRIPTION
**Pull request by vholland**

### CODE REVIEW

**Comment by RichardWallis** [comment]
Is there need for a QR Code equivalent?

~Richard

**Comment by mfhepp** [comment]
I would define this property in a way that it is a compatible with QR Codes. The Wikipedia entry for barcode seems to use such a broader notion.

https://en.wikipedia.org/wiki/Barcode

**Comment by chaals** [comment]
tentative +1 to @mfhepp - it's a "visual machine-readable code". 

On the other hand, if there are really only two subtypes and it is often important to distinguish, maybe we should make them explicit.

**Comment by danbri** [comment]
Even qr codes are used in many ways - let's avoid a hardcode taxonomy that will date quickly

**Comment by vholland** [comment]
I updated the definition to "visual machine-readable code such as a barcode or QR code".

**Comment by danbri** [comment]
Merged for review/discussion. Also note that we have 

<http://schema.org/ticketToken> <http://www.w3.org/2000/01/rdf-schema#comment> "Reference to an asset (e.g., Barcode, QR code image or PDF) usable for entrance." .

... in the schemas nearby. It seems complementary. We could add Barcode or CreativeWork to the range values for ticketToken but I don't think that is essential.

**Pull request merged**
