### PR TITLE
Fix (#1234) Show incoming properties for all layers

### PR DESCRIPTION
**Pull request by RichardWallis**

### CODE REVIEW

**Comment by danbri** [comment]
Merged. Can we have an entry for docs/releases.html please? (just type it here if you like)

**Comment by RichardWallis** [comment]
For docs/releases.html:
Enhance incoming properties display (_Instances of XXXX may appear as values for the following properties_) to include properties from extensions.

**Comment by danbri** [comment]
I've updated releases.html - https://github.com/schemaorg/schemaorg/commit/5a7cc17e64a0b68115df8b4c9c0a5f523367ab1b

**Comment by pmika** [comment]
This is an automatically generated message.

pmika@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Pull request merged**
