### PR TITLE
Fix to Book example makinging it mainEntity of WebPage

### PR DESCRIPTION
**Pull request by RichardWallis**
Fixed JSON-LD to reflect this
https://github.com/schemaorg/schemaorg/issues/644 (#644)

### CODE REVIEW

**Comment by danbri** [comment]
See http://webschemas.org/Book and http://webschemas.org/mainEntity 1st example (JSON).

**Comment by danbri** [comment]
(optionally) shall we do breadcrumb & ratingValue while we're at it?

**Comment by jvandriel** [comment]
I just noticed that the ```breadcrumb``` is falsly chained to schema.org/Book as opposed to schema.org/WebPage in the JSON-LD example. In Microdata and RDFa this has been done correctly.

**Comment by RichardWallis** [comment]
I'll fix the breadcrumb in JSON-LD

**Comment by RichardWallis** [comment]
Fixed - awaiting merge

**Comment by jvandriel** [comment]
Thanks.   :)

**Comment by danbri** [comment]
Fixed  #644

**Pull request merged**
