### PR TITLE
Issue #330: Added minimumRequiredPurchasePrice.

### PR DESCRIPTION
**Pull request by vholland**

### CODE REVIEW

**Comment by mfhepp** [comment]
Hi Vicky, I am not entirely sure whether I understand this proposal, but it you want to constrain the validity of a commercial offer to a minimum purchasing volume in monetary terms or units, then use http://schema.org/eligibleTransactionVolume or http://schema.org/eligibleQuantity.

**Comment by vholland** [comment]
The intention was more around the cost for delivery based on the purchase price. Online retailers often waive delivery charges for order over a certain amount. I may have a delivery charge of $10 for order less than $100, but no delivery charge for orders of $100 or more.

**Comment by mfhepp** [comment]
Hi Vicky:

On 13 Mar 2015, at 18:15, vholland <notifications@github.com> wrote:

> The intention was more around the cost for delivery based on the purchase price. Online retailers often waive delivery charges for order over a certain amount. I may have a delivery charge of $10 for order less than $100, but no delivery charge for orders of $100 or more.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

This can be covered with the existing vocabulary. See below for an example.

The only area for improvement I see is that the definition of intervals in prices and quantitative values has currently support for including endpoints via min/max, not for excluding endpoints, so we have to use

<meta itemprop="maxPrice" content="99.99">

to indicate "less than 100.

We could add maxPriceExcludes/minPriceExcludes/maxValueExcludes/minValueExcludes properties to schema.org, but I would rather recommend markup recipes as the ones proposed. 

Martin


<div itemscope itemtype="http://schema.org/Offer">
  <div itemprop="name">Hepp Personal SCSI Controller Card</div>
  <div itemprop="description">The Hepp Personal SCSI is a 16-bit add-on card that allows 
attaching up to seven SCSI devices to your computer.</div>

  <div itemscope itemprop="priceSpecification" 
       itemtype="http://schema.org/UnitPriceSpecification">Price: 
    <meta itemprop="priceCurrency" content="USD">$  
    <span itemprop="price">25.99</span>
  </div>

  Delivery costs:
  <div itemscope itemprop="priceSpecification" 
       itemtype="http://schema.org/DeliveryChargeSpecification"> 
    <meta itemprop="priceCurrency" content="USD"> 
    <meta itemprop="price" content="0">Free</span> for orders of 
    <div itemprop="eligibleTransactionVolume" itemscope itemtype="http://schema.org/PriceSpecification">
    	<meta itemprop="priceCurrency" content="USD">$
    	<span itemprop="minPrice">100</span> and more
	</div>
  </div>

  <div itemscope itemprop="priceSpecification" 
       itemtype="http://schema.org/DeliveryChargeSpecification"> 
    <meta itemprop="priceCurrency" content="USD">$
    <span itemprop="price">10</span> for orders below 
    <div itemprop="eligibleTransactionVolume" itemscope itemtype="http://schema.org/PriceSpecification">
    	<meta itemprop="priceCurrency" content="USD">$
    	<meta itemprop="maxPrice" content="99.99">100.
	</div>
  </div>
    
  </div>

...
</div>




-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by mfhepp** [comment]
So in short, http://schema.org/eligibleTransactionVolume is your friend. 

;-)

If you want to say "free shipping for ten pieces or more", you can use http://schema.org/eligibleQuantity.

And of course you can constrain such shipping charge information by adding regions (e.g. US for USA or US-Ca for California) via

    http://schema.org/eligibleRegion

and carrier information via

    http://schema.org/appliesToDeliveryMethod


You can also say "free shipping until December 15, 2015" by attaching 

    http://schema.org/validThrough

to the 

    http://schema.org/DeliveryChargeSpecification

If you attached it to the Offer or UnitPriceSpecification, you would constrain the validity of the whole offer or the unit price information.

Similar patterns work for payment charges.



Martin

PS: GoodRelations... batteries included ;-)

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by vholland** [comment]
http://schema.org/eligibleTransactionVolume works for me. I will close the pull request.

**Pull request closed without merging**
