### PR TITLE
Auto final fixes

### PR DESCRIPTION
**Pull request by W3C-GAO**
The following issues are addressed by that pull request:
- #704 (master issue)
- #899
- #898
- https://lists.w3.org/Archives/Public/public-gao/2015Nov/0006.html

### CODE REVIEW

**Comment by mfhepp** [comment]
Thanks - a few questions:

1. Is this version somewhere online on a demo site (on appspot)?
2. From the diff, I think that vehicleSpecialUsage lacks a comment (not 100 % sure).
3. Did you double-check the examples for mentions of the elements removed from core or renamed in the extension?

**Comment by W3C-GAO** [comment]
@mfhepp
Ad 1. No
Ad 2. vehicleSpecialUsage in the core has a comment. vehicleSpecialUsage in auto extension does not have a comment.
Ad 3. Yes

**Comment by mfhepp** [comment]
@RichardWallis @danbri I think this extension is the first to modify the range of a property from core; can you have a look whether this is fine? 

If I understand correctly, the proposal is to have just Text as the range in core and Text OR http://auto.schema.org/CarUsageType.

It might be simpler to move vehicleSpecialUsage to the extension completely and removing it from core.

A counter argument is that in the past, we wanted all properties that are useful for typical car listing sites in the core and externalize only those relevant mostly for manufacturer pages.

**Comment by mfhepp** [comment]
@W3C-GAO It would be nice to have an appspot version available for review. It should not be a big issue to set up and will be much easier for reviewers than looking at the pure code.

**Comment by RichardWallis** [comment]
If specialUsage is defined as in the core with a range of Text,  you should
only need to define a range of CarUsageType in its definition in the
extension to achieve that objective.  The site will sum them together at
run time.

~Richard

**Comment by trypuz** [comment]
@RichardWallis, there is no specialUsage in the core (we had it in the auto extension before but it was changed to vehicleSpecialUsage). So now, we have vehicleSpecialUsage both in the core and in the extension. vehicleSpecialUsage in the core has just Text as the range; in the extension we only added a range of CarUsageType in its definition.

**Comment by RichardWallis** [comment]
OK, sorry I was looking at the pre name change version.

Principle is the same however.

If vehicleSpecialUsage is defined as in the core with a range of Text,  you
should only need to define a range of CarUsageType in its definition in the
extension to achieve that objective.  The site will sum them together at
run time.


Which as you say is what is in pull request #922
<https://github.com/schemaorg/schemaorg/pull/922>

~Richard.

**Comment by trypuz** [comment]
We created a demo site on appspot of this version of auto extension. Here it is: http://sdo-gao.appspot.com

**Comment by danbri** [comment]
Note that this update wipes out specialUsage; normally we leave the old definition in place and indicate the newer with 'supersededBy'. In this case, since it was in the stated 'preview' release of the extension, I think we can get away with it as usage levels of specialUsage are likely very low. If it turns out to have been used significantly anywhere we can always add the old name back into the schemas for the record.

**Comment by mfhepp** [comment]
Ooops - I did not remember that we agreed to remove specialUsage. Can anybody point me to the discussion? For rental cars, it is a pretty important information (and mandatory in many countries). Didn't we probably agree to move it to Product?

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by sdml** [comment]
@mfhepp We changed the name of specialUsage to vehicleSpecialUsage. See #705 and #898.

**Comment by danbri** [comment]
Yes, just a name change - sorry should have been clearer

**Comment by danbri** [comment]
http://webschemas.org/docs/releases.html#g922

**Pull request merged**
