### PR TITLE
added CompoundPriceSpecification

### PR DESCRIPTION
**Pull request by mfhepp**
This pull requests addresses #829.

It fixes a major inconsistency in the GoodRelations pricing model and is needed for hotels and rental cars.

### CODE REVIEW

**Comment by rvguha** [comment]
This might break some of the applications that currently use schema.org
price specification.

Lets please get their ok before making these changes

guha

**Comment by mfhepp** [comment]
Dear Guha:
Of course, it is good to check that it won't break existing apps, but I am pretty sure that there is almost no markup in the wild to far that properly uses multiple price components in the existing form. So the focus of a cross-check should be that an app that currently understands a single UnitPriceSpecification will also be able to consider multiple components attached via the new CompoundPriceSpecification type.

Martin

-----------------------------------
martin hepp  http://www.heppnetz.de
mhepp@computer.org          @mfhepp

**Comment by rvguha** [comment]
Breaking usage of existing markup is not the only problem. Another problem
that occurs is that new (and some old) publishers start switching to the
new way of expressing things, which old apps cannot (yet) consume.

guha

**Comment by vholland** [comment]
Do you have examples of this new schema? It is complex, so authors are probably not going to use it correctly with only the definition to go by.

**Comment by mfhepp** [comment]
I have closed and updated this pull request, see https://github.com/schemaorg/schemaorg/pull/994 for the correct one.

**Pull request closed without merging**
