### PR TITLE
Extension for schema.org/Skiresort

### PR DESCRIPTION
**Pull request by eliaskaerle**
# schema.org/SkiResort - Extension
## abstract

This pull request suggests an extension to the class **schema.org/SkiResort** to add functionality for annotating **SkiLifts** and **SkiSlopes**. This topic was discussed on the public schema.org mailing list and the suggestions made by members of the list to improve this extension were incorporated (see [public-schemaorg](https://lists.w3.org/Archives/Public/public-schemaorg/2016Jul/), starting on Wed, 20 July 2016).
## why

We were annotating the website of a tourism region and came across the need to annotate ski resorts. Unfortunately there was no possibility in schema.org to annotate ski lifts and ski slopes. So we made the extension of schema.org/SkiResort to annotate ski lifts and ski slopes.
## how
- **schema.org/SkiResort** was extended by two properties
- **two new** classes were introduced with **eight new properties in total**
### list of new classes:
- [**schema.org/SkiLift**: https://sdo-skiresort-1378.appspot.com/SkiLift](https://sdo-skiresort-1378.appspot.com/SkiLift)
- [**schema.org/SkiSlope**: https://sdo-skiresort-1378.appspot.com/SkiSlope](https://sdo-skiresort-1378.appspot.com/SkiSlope)
### list of new properties:
- [**schema.org/liftType**: https://sdo-skiresort-1378.appspot.com/liftType](https://sdo-skiresort-1378.appspot.com/liftType)
- [**schema.org/transportCapacity**: https://sdo-skiresort-1378.appspot.com/transportCapacity](https://sdo-skiresort-1378.appspot.com/transportCapacity)
- [**schema.org/elevationStart**: https://sdo-skiresort-1378.appspot.com/elevationStart](https://sdo-skiresort-1378.appspot.com/elevationStart)
- [**schema.org/elevationEnd**: https://sdo-skiresort-1378.appspot.com/elevationEnd](https://sdo-skiresort-1378.appspot.com/elevationEnd)
- [**schema.org/length**: https://sdo-skiresort-1378.appspot.com/length](https://sdo-skiresort-1378.appspot.com/length)
- [**schema.org/numberOfStops**: https://sdo-skiresort-1378.appspot.com/numberOfStops](https://sdo-skiresort-1378.appspot.com/numberOfStops)
- [**schema.org/slopeNumber**: https://sdo-skiresort-1378.appspot.com/slopeNumber](https://sdo-skiresort-1378.appspot.com/slopeNumber)
- [**schema.org/difficulty**: https://sdo-skiresort-1378.appspot.com/difficulty](https://sdo-skiresort-1378.appspot.com/difficulty)
- [**schema.org/hasSkiLift**: https://sdo-skiresort-1378.appspot.com/hasSkiLift](https://sdo-skiresort-1378.appspot.com/hasSkiLift)
- [**schema.org/hasSkiSlope**: https://sdo-skiresort-1378.appspot.com/hasSkiSlope](https://sdo-skiresort-1378.appspot.com/hasSkiSlope)
### see figure:

Diagram of the Extension
## online documentation
- [**Documentation** (first version): https://sdo-skiresort-1378.appspot.com/docs/skiresort.html](https://sdo-skiresort-1378.appspot.com/docs/skiresort.html)
- [**schema.org/SkiResort**: https://sdo-skiresort-1378.appspot.com/SkiResort](https://sdo-skiresort-1378.appspot.com/SkiResort)
- [**schema.org/SkiLift**: https://sdo-skiresort-1378.appspot.com/SkiLift](https://sdo-skiresort-1378.appspot.com/SkiLift)
- [**schema.org/SkiSlope**: https://sdo-skiresort-1378.appspot.com/SkiSlope](https://sdo-skiresort-1378.appspot.com/SkiSlope)

### CODE REVIEW

**Comment by eliaskaerle** [comment]
@RichardWallis @danbri any thoughts on merging my pull request after the discussion on the mailing list last month? thanks!

**Comment by eliaskaerle** [comment]
Hi,
I would like to know if there is anything I can do to proceed with my ski resort proposal. We already had a discussion on the mailing list which came to no real conclusion. Any thoughts?
Thanks!

**Comment by thadguidry** [comment]
+1 to add this to pending for now.

@eliaskaerle Can you change the definitions for elevationEnd and elevationStart to be:

Elevation at the end or TOP of the lift.
Elevation at the start or BOTTOM of the lift.

**Comment by vholland** [comment]
A few quick comments:

- Can we rename 'liftType' to something less generic like 'skiLiftType'?
- Can we reuse http://schema.org/distance rather than introduce 'length'?
- Can we rename 'difficulty' to something less generic?
- What is the slope number? The description and examples don't really explain what is being conveyed.

**Comment by thadguidry** [comment]
'difficulty' should be renamed 'skiSlopeDifficulty'  because its really the slope number that has a difficulty rating.

**Comment by eliaskaerle** [comment]
@thadguidry, @vholland, thanks, I agree and will implement the changes as suggest.

@vholland: the slope number is the primary key or UID for slopes inside a ski resort. (see this slope map for example: http://www.skiresort.de/uploads/tx_mgskiresort/obergurgl.jpg ) But I agree that the description is poor, I'll update that.

**Comment by eliaskaerle** [comment]
Any further suggestions, comments, issues or potential changes?

**Comment by eliaskaerle** [comment]
Hi @RichardWallis and @danbri,
is there anything I can do to advance with this pull request or is it finally ready for being merged?
Thanks!

**Comment by chaals** [comment]
The `skiSlopeDifficulty` is related to difficulty for things like instructions - cooking recipes, explanations about how to replace a carburettor, etc.

Does it make more sense to have a general `DifficultyRating` and then describe known schemes such as ski slopes?

**Comment by Dataliberate** [comment]
> Does it make more sense to have a general DifficultyRating and then describe known schemes such as ski slopes?


+1

**Comment by danbri** [comment]
agree re difficulty - we should address it alongside 

https://github.com/schemaorg/schemaorg/issues/647 and related

**Comment by eliaskaerle** [comment]
Ok. Should I take 'skiSlopeDifficulty' out temporarily, that the extension can make it into 3.2, or do we set up a 'DifficultyRating' right away?

**Comment by eliaskaerle** [comment]
Dear @RichardWallis , can you tell me why you closed that pull request? Do I have to file a new one? I would still like to have this terms in schema.
Thanks, best, Elias

**Comment by RichardWallis** [comment]
@eliaskaerle Sorry, the automatic close was an unexpected consequence of removing a stale branch (_schemaorg:sdo-makemake_) that was way behind the current master branch.

It should be recreatable by bringing _eliaskaerle:sdo-makemake_ in line wih _schemaorg:master_ and creating a new PR.

**Comment by eliaskaerle** [comment]
@RichardWallis I see, thanks for the answer. I'll do that!

**Pull request closed without merging**
