### PR TITLE
Cleanup the copystaticdocsplusinsert python code.

### PR DESCRIPTION
**Pull request by MatthiasWiesmann**
* Systematically use os.path.join for joining paths.
* Use os.EX_ exit values.
* Added some documentation for functions.
* Fixed spacing.
* Use `fronzenset` for immutable collection.
* Avoid uncessary variable in the root namespace.

### CODE REVIEW

**Review by RichardWallis — DISMISSED** [review]

**Comment by RichardWallis** [comment]
@MatthiasWiesmann Thanks for your cleanup efforts.

Spotted a small error introduced in your changes.:
Because you have changed the variable 'f' to 'f_path' (line 30) the later call to open() (line 33) contains an invalid variable name.

I presumed that this had been tested prior to submission.

**Comment by MatthiasWiesmann** [comment]
Apologies, I screwed up my branches.

**Comment by RichardWallis** [comment]
@MatthiasWiesmann Apply the fix to this branch an we can approve and merge it

**Comment by MatthiasWiesmann** [comment]
Done

**Comment by RichardWallis** [comment]
@MatthiasWiesmann This PR hasn't been merged into the main branch yet - my fault I missed your fix arriving in the branch.

Do you want to reopen it and I'll merge it.

~Richard

**Pull request merged**
