### PR TITLE
Added startTime / endTime to Schedule

### PR DESCRIPTION
**Pull request by RichardWallis**
Implements issue #2493

### CODE REVIEW

**Comment by RichardWallis** [comment]
@ldodds @vholland 

Is this change OK with you?

**Comment by vholland** [comment]
We just added startDate/endDate. Do we still need this?

**Comment by RichardWallis** [comment]
Yes we do still need this.

startDate/endDate is for the start/end of the schedule
startTime/endTime is the start/end of the event on the scheduled day.

See [examples](https://schema.org/Schedule#Event-gen-241) already published

**Comment by vholland** [comment]
That makes sense. Thanks.

**Comment by danbri** [comment]
@tmarshbing pointed out that we really need better general documentation of modeling/patterns here.  I think the discussion above proves that point. /cc @ldodds @lucy-kind

**Pull request merged**
