### PR TITLE
Move Fibo.schema.org proposal in to pending

### PR DESCRIPTION
**Pull request by RichardWallis**
Replaces PR (#1254)  (merge into sdo-makemake)

### CODE REVIEW

**Comment by RichardWallis** [comment]
See conversations on PR (#1254) & Issue (#1253)
This is an update to the original proposal PR (#1163) - A Pull Request constituting a proposal for a FIBO extension to Schema.org from the [Financial Industry Business Ontology Community Group](https://www.w3.org/community/fibo/).

Changes from original:
- Proposing a prerelease move into pending.schema.org
- Moving ServiceChannel specific proposals into a separate proposal - PR(#1298)
- Update property names to be more focused on the area they are used.

**Comment by rvguha** [comment]
The schema changes look good. 

Examples: Lets use fictitious entities in our examples.

**Comment by RichardWallis** [comment]
No problem on the fictional examples.

Will update these in next couple of days and also resolve the merge conflict.

**Comment by danbri** [comment]
My review notes:

* PR includes a needless (and conflicting) sdoapp.py edit - can you remove that please?
* let's put this into pending.schema.org first, with a view to moving it along towards a hosted extension subdomain a release or two after that.
* I would prefer its eventual home to be under something like "finance.schema.org". We have merged in contributions from BBC, EBU, MusicBrainz, GoodRelations, GS1 and many others in previous releases without creating a project-acronym-based subdomain. I appreciate the desire for fibo.schema.org but I suggest it is better to keep collaboration and derivation acknowledgments elsewhere (in human-facing text and in machine definitions, but not in subdomains).

**Comment by sopekmir** [comment]
Hi Dan,
Sorry for late reply. We will remove the edit and we are also making our examples fictional (after Guha's request).
As for placing it into pending - that's great and this is exactly what we expected to happen. Thanks !

When it comes to the change to the name of the extension, I hope it will not be a problem for the other members of the community which brought the concept of the extension to life. I will start my consultations asap.

**Comment by sopekmir** [comment]
BTW, I just got info from Richard that the requested changes has been made! Thanks Richard !

**Comment by Dataliberate** [comment]
Now issues raised by Guha have been addressed, can we merge this now.

**Comment by trypuz** [comment]
@danbri, @RichardWallis, what is the next step? Is there anything FIBO community can do to move the FIBO extension from "pending" towards a hosted extension?

**Comment by sopekmir** [comment]
I'm aware about reservations to move the extension to the one named by "fibo". Indeed, living between the two worlds, I must admit we had long lasting difficulties with the FIBO team to give us proper, canonical FIBO URIs, so that we could amend the extension documentation and have a "hard link" between the extension and the ontology. However, as it is more problematic for teh extension to stay in "pending" for so long, than having a permanent name, maybe we would indeed go for finance.schema.org for the upcoming edition? Is it possible?

**Pull request merged**
