### PR TITLE
Issue #2646: Added AmpStory

### PR DESCRIPTION
**Pull request by vholland**

### CODE REVIEW

**Comment by RichardWallis** [comment]
Checks are failing on this PR.

Bit of an odd failure:
```
INFO:test_graphs:Term 'http://schema.org/EducationalOccupationalProgram' has none-matching label: 'AmpStory'
FAIL
```

**Comment by vholland** [comment]
Oops. I fixed it. And now everyone knows I mostly code by copy & paste.

**Comment by danbri** [comment]
@vholland could you PR something for docs/releases.html too?

**Comment by danbri** [comment]
or just type it here :)

**Comment by danbri** [comment]
I've merged this, but suggest we consider prepending something referencing https://wp.stories.google/ into "A creative work with a visual storytelling format intended to be viewed online, particularly on mobile devices." 

more details at https://amp.dev/documentation/components/amp-story/#metadata-guidelines

Those docs describe a custom element `<amp-story>` which gives us a good technical reference at least.

**Pull request merged**
