### PR TITLE
D3.js visualization of schema.org hierarchy

### PR DESCRIPTION
**Pull request by fabiovalse**
This pull request consists of a D3.js sunburst visualization for substituting the HTML indented tree of the schema.org hierarchy displayed [here](http://schema.org/docs/full.html).

### CODE REVIEW

**Comment by Dataliberate** [comment]
Do you have a test instance of this that we can view?

**Comment by fabiovalse** [comment]
Unfortunately it was running on my laptop. If you can't run it, I can try to put it on a server in the next days.

**Comment by Dataliberate** [comment]
Managed to get it going locally by cloning from your [fabiovalse] fork.

Looks nice, I could imagine it being added as an optional view, but I could not see it being a default view that would be used to navigate around the hierarchy of Types. 

Couple of implementation points:  
* The tool-tip texts do not include the Type name so are not very helpful. 
* The display does not reflect the view selection buttons - try it at http://bib.localhost:8080/docs/full.html and select "Extension 'bib'"
* The link, when clicking on a segment in the sunburst, is hard coded to go to http://schema.org...  the rest of the application uses relative URLs to enable testing, operation within extensions, etc.

~Richard.

**Comment by fabiovalse** [comment]
Ok, so do you have some solution in mind for the optional view? Something you prefer? A tab menu where you can switch between the main and the optional view?

**Comment by Dataliberate** [comment]
Good question that ties in with (#879). 
 
We have the need to enable browsing through the Type hierarchy of the core vocabulary and each and all extensions for several uses. To answer the _what are the subtypes of CreativeWork_ style questions; Identify what core terms are super-types for an extension; as well serendipitous discovery aided by a visual representation.

We also need to be aware of (#718) accessibility issues which still needs some efforts to resolve.

I have no firm preferences as to how that page is remodelled. My current thoughts are that you should be able to choose what to display - core, extension(s), data types, combinations thereof - and then variations  of display (two or three) defaulting to the simplest/most accessible first.

**Comment by danbri** [comment]
I'm sorry, I'd missed this one.  Let's consider it as addressing https://github.com/schemaorg/schemaorg/issues/879

Just tried viewing it (http://localhost:8080/docs/full.html is entry point?) via "git clone https://github.com/fabiovalse/schemaorg" ...  however the page only displays up until "Select vocabulary view: Core vocabulary   Core plus all extensions" and there's an error in the console:

>    sunburst.js:58 Uncaught TypeError: Cannot read property 'size' of null(anonymous function) @     sunburst.js:58(anonymous function) @ sunburst.js:204
58sunburst.js:38 Uncaught TypeError: ".semantic_zoom".attr is not a function(anonymous function) @ sunburst.js:38t @ d3.v3.min.js:1(anonymous function) @ d3.v3.min.js:1c @ d3.v3.min.js:3p @ d3.v3.min.js:3(anonymous function) @ d3.v3.min.js:1

**Comment by danbri** [comment]
Ping @fabiovalse

**Comment by mik-laj** [comment]
What's up with this?

**Comment by danbri** [comment]
@fabiovalse did you continue to explore this?

**Comment by danbri** [comment]
closing for now...

**Pull request closed without merging**
