### PR TITLE
Financial (FIBO) proposals for core vocabulary

### PR DESCRIPTION
**Pull request by Dataliberate**
This Pull Request constitutes a small proposal for enhancements to the core of Schema.org from the [Financial Industry Business Ontology Community Group](https://www.w3.org/community/fibo/).  

The proposal offered by the Group is based on the work of the [Financial Industry Business Ontology project](http://www.fibo.org/schema) to extend the capabilities of Schema.org aligned with the Financial Industry Business Ontology (FIBO).  This has been a team effort utilising the expert knowledge and know-how of members of the FIBO Content Team involved in creating the Financial Industry Business Ontology, working with others familiar with Schema.org including Mirek Sopek, Richard Wallis and Martin Hepp.

The proposal consists of the following elements in the schema.rdfa file and some examples in sdo-fibo-examples.txt.  
* __New Types:__ MonetaryAmount, FinancialProduct, BankAccount, DepositAccount, LoanOrCredit, InvestmentOrDeposit, CurrencyConversionService.
* __New Properties:__ annualPercentageRate, feesAndCommissionsSpecification, interestRate, leiCode, loanTerm, maxAmount, minAmount, requiredCollateral.
* __Updated Type:__ CreditCard
* __Updated Properties:__ amount, acceptedPaymentMethod, currency.

More detail and links to the definitions in a test version of schema.org (<http://sdo-fibo.appspot.com/>) are available in the [Group Wiki](https://www.w3.org/community/fibo/wiki/Main_Page).

The proposal contains Types and Properties that will generally enhance capability in describing things of a financial nature but without introducing too much financial industry specific detail.  We also took the opportunity to extend the domain of several properties such as logo, brand, and isRelatedTo to help the description of Services as well as Products.  The future intension is to explore more detailed proposals that would form a hosted extension that builds upon these generally useful ones.

We look forward to comments, suggestions and questions that will help these enhancements become part of the vocabulary.

Richard Wallis.

### CODE REVIEW

**Comment by danbri** [comment]
Thanks for this. Is there a corresponding issue describing the needs that this implementation addresses? If not could you file something? It is best not to have dangling solutions filed solely as pull requests...

**Comment by mfhepp** [comment]
I created a respective issue to manage this work, see #969

**Comment by danbri** [comment]
Not a full review, but from a first pass: re "LoanOrCredit, InvestmentOrDeposit" ... can you try to come up with a name that doesn't include "Or" in it?

**Comment by mfhepp** [comment]
I think the current names are better than using a single super-term. We have to make sure people from the industry find the proper concepts. LoanOrCredit are two common words for such financial products where you get temporary access to an amount of money. We could, if absolutely needed, condense it to "Loan" (see also https://en.wikipedia.org/wiki/Loan).

InvestmentOrDeposit was chosen as an intuitive super-term for all financial products in which the client gives money for a future return. IMO, investment is more natural if the revenues are in the focus, while deposit is more common when the safe repayment of the money is the primary goal. If I deposit money, I want to get it back. If I make an investment, I am mainly looking for earnings from giving away the money.

**Comment by Dataliberate** [comment]
I support Martin in his description and analysis.

The two super-terms were chosen to support the common properties across
current and future individual financial product types.  These naturally
separate into the two product areas he describes for *temporary access to
an amount of money* and for *giving money for future return*.

Although logically two classes of products, the financial industry further
subdivide them into loans/credit and investment/deposit products which are
the names they would use when looking for appropriate terms.  If in the
real world, actual products cleanly dropped into those 4 categories we may
have had the option to go for four super-types instead of two.  However it
is clear that some products exhibit attributes of investments and deposits,
etc.

If we were looking at individual types I would share your discomfort at the
proposed naming. As these are proposed as super-types for more specific
individual subtypes I believe they are named appropriately.

~Richard.

Richard Wallis
Founder, Data Liberate
http://dataliberate.com
Linkedin: http://www.linkedin.com/in/richardwallis
Twitter: @rjw

**Comment by Dataliberate** [comment]
Couple of examples of live commercial sites using the terms in this proposal.  Both having JSON-LD inserts which I have extracted and attached for reference:
* https://www.bancofcal.com/lending/  -  Extract: [banclending.txt](https://github.com/schemaorg/schemaorg/files/179601/banclending.txt)

* https://www.banchomeloans.com/  -  Extract: [banchomelones.txt](https://github.com/schemaorg/schemaorg/files/179603/banchomelones.txt)

**Comment by Dataliberate** [comment]
Git reports conflicts with this PR in its current state.  
In terms of the proposed changes it is up to date.
However investigation shows that changes in a part of schema.rdfa are not fully understood by the git merge mechanism, and would need a little manual intervention.

**Comment by Dataliberate** [comment]
Background to this proposal and links to examples are available on a wiki page in the FIBO W3C Wiki Here: https://www.w3.org/community/fibo/wiki/Main_Page

**Pull request merged**
