### PR TITLE
Adds BoatTerminal, BoatReservation and BoatTrip (#1755)

### PR DESCRIPTION
**Pull request by magico**
Implements #1755

### CODE REVIEW

**Comment by danbri** [comment]
@RichardWallis - can you take a look at what's up here?

**Comment by RichardWallis** [comment]
Will do.

**Comment by danbri** [comment]
I've taken this and recoded it in Turtle form (we switched formats recently)

https://github.com/schemaorg/schemaorg/blob/master/data/ext/pending/issue-1755.ttl

**Comment by danbri** [comment]
Queued for release in version 9.0 next week, https://github.com/schemaorg/schemaorg/issues/2634

**Pull request closed without merging**
